---
title: "Check differential flux analysis results of Vero E6 cell remdesivir treatment data"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
```

```{r}
library(my.utils)
library(gembox)
library(rio)
```

```{r}
load("../GEM_remdesivir/dflux.res.RData")

fmat0 <- rbind(control=df.res$c2d$mean0,
               remdesivir=df.res$c2d$mean1,
               virus=df.res$c2v$mean1,
               `virus+remdesivir`=df.res$c2vd$mean1)
```

PCA plot
```{r, fig.width=1.3, fig.height=1.2}
#tmp <- fmat0[, apply(fmat0,2,uniqueN)>1]
#plot.pca(tmp, color=rownames(fmat0), scale=FALSE) + labs(color="Group")
plot.pca(fmat0/100, color=rownames(fmat0), label=rownames(fmat0), scale=FALSE) + xlim(c(-50,50)) + ylim(c(-50,50)) + thm(lgd="none")
```

Pathway enrichment of DF reactions between ctrl and virus+remdesivir
```{r}
tmp <- df.res$c2vd[dir!=0 & abs(rel.diff)>0.25 & abs(diff.mean)>1e-5, rxn]
length(tmp)
rset <- subsystems2gsets(recon1)
( enr.res.c2vd <- enrich.gsets(tmp, rset, recon1$rxns)[padj<0.1] )
```

Pathway enrichment of DF reactions between ctrl and infected
```{r}
tmp <- df.res$c2v[dir!=0 & abs(rel.diff)>0.25 & abs(diff.mean)>1e-5, rxn]
length(tmp)
( enr.res.c2v <- enrich.gsets(tmp, rset, recon1$rxns)[padj<0.1] )
```

Pathway enrichment of DF reactions between ctrl and remdesivir
```{r}
tmp <- df.res$c2d[dir!=0 & abs(rel.diff)>0.25 & abs(diff.mean)>1e-5, rxn]
length(tmp)
( enr.res.c2d <- enrich.gsets(tmp, rset, recon1$rxns)[padj<0.1] )
```

```{r}
intersect(enr.res.c2vd$gene.set, enr.res.c2v$gene.set)
setdiff(enr.res.c2vd$gene.set, enr.res.c2v$gene.set)
intersect(setdiff(enr.res.c2vd$gene.set, enr.res.c2v$gene.set), enr.res.c2d$gene.set)
```

```{r, fig.width=2.3, fig.height=1.2}
tmp <- enr.res.c2vd[padj<0.1]
tmp[, nlp:=-log10(padj)]
tmp[, gene.set:=factor(gene.set, levels=gene.set)]

p <- ggplot(tmp) +
  ylab("Odds Ratio") +
  geom_point(aes(x=gene.set, y=odds.ratio, color=nlp, size=overlap.size)) + 
  scale_color_continuous(low="grey", high="red3", name=expression(-log[10]*P[adj])) + 
  scale_size_continuous(name="overlap size", range=c(1,4)) +
  geom_hline(yintercept=1, linetype="dashed", color="grey") +
  #annotate("text", x=1.7, y=1.8, label="odds ratio>1", size=2.5, color="grey30") +
  theme_classic() +
  thm(y.tit=9, y.txt=7, x.tit=NULL, x.txt=list(size=7,angle=30,hjust=1), lgd.tit=7, lgd.txt=6, lgd.key=10, lgd.margin=c(20,0,0,0), plt.margin=c(0,0,0,25)) + theme(legend.spacing=unit(0,"pt"))
p
```

Export tables:
```{r}
mapp <- c("c2v"="virus.vs.control", "c2vd"="virus+remdesivir.vs.control", "c2d"="remdesivir.only.vs.control", "v2vd"="virus+remdesivir.vs.virus", "d2vd"="virus+remdesivir.vs.remdesivir.only")
tmp <- df.res[grep("0$", names(df.res))]
names(tmp) <- str_sub(names(tmp), 1, -3)
tmp1 <- rbindlist(tmp, idcol="comparison")
tmp1[, comparison:=mapp[comparison]]

tmp <- lapply(tmp, function(x) enrich.gsets(x[dir!=0 & abs(rel.diff)>0.25 & abs(diff.mean)>1e-5, rxn], rset, recon1$rxns))
tmp2 <- rbindlist(tmp, idcol="comparison")
tmp2[, comparison:=mapp[comparison]]

tmp <- list(S9A=tmp1, S9B=tmp2)
rio::export(tmp, "Table S9_Differential flux and pathway enrichment results between pairs of conditions for remdesivir-treated Vero E6 cell samples.xlsx")
```



